
/* Main.ino file generated by New Project wizard
 *
 * Created:   Thu Oct 31 2024
 * Processor: Arduino Uno
 * Compiler:  Arduino AVR (Proteus)
 */

// Peripheral Configuration Code (do not edit)
//---CONFIG_BEGIN---
#pragma GCC push_options
#pragma GCC optimize ("Os")

#include <core.h> // Required by cpu
#include <cpu.h>

#pragma GCC pop_options

// Peripheral Constructors
CPU &cpu = Cpu;

void peripheral_setup () {
}

void peripheral_loop() {
}
//---CONFIG_END---
#define ROW_MASK 0xF0    
#define COL_MASK 0x07   
//#include <avr/io.h>
//#include <util/delay.h>

uint8_t led_7_segment[10] = {
    0x3F, // 0
    0x06, // 1
    0x5B, // 2
    0x4F, // 3
    0x66, // 4
    0x6D, // 5
    0x7D, // 6
    0x07, // 7
    0x7F, // 8
    0x6F  // 9
};

// Hàm quét ma tr?n nút nh?n

void setup () {
   peripheral_setup();
    //DDRB = 0x00;
    PORTB = 0xFF; // Kích ho?t pull-up cho t?t c? các chân

    // C?u hình PORTC làm ngõ ra (output) cho LED 7 do?n
    //DDRC = 0xFF;
    PORTC = 0x00;
    

    // Kh?i t?o các port
    init_ports();


}

   
void loop() {
//peripheral_loop();
uint8_t key;
key = scan_matrix();

        if (key != 0xFF) {
            // N?u có nút nh?n, hi?n th? s? tuong ?ng trên LED 7-segment
            display_number(key);
        }

        // Delay d? tránh quét quá nhanh
        _delay_ms(100);
    

   
}
uint8_t led7segment[10] = {
    0b00111111, // 0
    0b00000110, // 1
    0b01011011, // 2
    0b01001111, // 3
    0b01100110, // 4
    0b01101101, // 5
    0b01111101, // 6
    0b00000111, // 7
    0b01111111, // 8
    0b01101111  // 9
};

void init_ports() {
    // C?u hình c?t (PB0, PB1, PB2) là OUTPUT
    DDRB |= (1 << PB0) | (1 << PB1) | (1 << PB2);
    // C?u hình hàng (PB3, PB4, PB5, PB6) là INPUT v?i pull-up
    DDRB &= ~((1 << PB3) | (1 << PB4) | (1 << PB5) | (1 << PB6));
    PORTB |= (1 << PB3) | (1 << PB4) | (1 << PB5) | (1 << PB6); // B?t pull-up cho các hàng

    // C?u hình LED 7-segment (PC0 d?n PC6) là OUTPUT
    DDRC = 0xFF;
}

uint8_t scan_matrix() {
    uint8_t row, col;

    // Quét qua các c?t
    for (col = 0; col < 3; col++) {
        // Ð?t c?t hi?n t?i xu?ng LOW (b?t c?t)
        PORTB &= ~(1 << (PB0 + col));

        // Ki?m tra các hàng
        for (row = 0; row < 4; row++) {
            if (!(PINB & (1 << (PB3 + row)))) { // Ki?m tra n?u nút nh?n du?c nh?n
                return (row * 3 + col); // Tr? v? s? nút nh?n (0 d?n 11)
            }
        }

        // Ð?t c?t l?i lên HIGH (t?t c?t)
        PORTB |= (1 << (PB0 + col));
    }

    return 0xFF; // Không có nút nh?n nào
}

void display_number(uint8_t number) {
    // Hi?n th? s? trên LED 7-segment
    if (number < 10) {
        PORTC = led7segment[number];
    }
}
















































/******************************************************************************

                            Online C Compiler.
                Code, Compile, Run and Debug C program online.
Write your code in this editor and press "Run" button to compile and execute it.

*******************************************************************************/

#include <stdio.h>
#include <string.h>
#include <stdint.h>

char message[] = "     hello    world";
uint8_t flag = 0, i =0;
char format[50];
char *mess = message, *ptr = format;

int main()
{
    printf("%s\n", message);
    while(*mess != '\0')
    {
        if((*mess == ' ') && (flag == 0))
        {
            flag = 1;
            format[i] = *mess;
            i++;
            mess++;
        }
        else if((*mess == ' ') && (flag == 1))
        {
            mess++;
        }
        else
        {
            flag = 0;
            format[i] = *mess;
            i++;
            mess++;
        }
    }
    ptr = format;
	while(*ptr != '\0')
	{
		printf("%c",*ptr);
		ptr++;
	}
}